'''
Gamba Game - Created by Micah Perteet and Isaac Franklin for APCSP 2025-26
Front end created by Micah Perteet
Backend and specified images created by Isaac Franklin
'''

# --- IMPORTS ---
import pygame
import pygame_menu
import random as rand
import numpy as np

# import test
if not pygame.font:
    print("Warning: fonts disabled")

# --- INITS ---
pygame.init()

# --- CONSTANTS ---
# Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
BG_GRAY = (211, 211, 211)

# Window constants
SCREEN_WIDTH = 1100
SCREEN_HEIGHT = 800
SCREEN_TITLE = "Gamba Game"
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)
CENTER = (SCREEN_WIDTH/2, SCREEN_HEIGHT/2)
FPS = 60

# Text setup
FONT_SIZE = 40
FONT = pygame.font.Font(None, FONT_SIZE)

TEXT_X_MARGIN = 5
TEXT_Y_MARGIN = 5
MONEY_TEXT_POSITION = (TEXT_X_MARGIN, TEXT_Y_MARGIN)

SCREEN = pygame.display.set_mode(SCREEN_SIZE)
pygame.display.set_caption(SCREEN_TITLE)
CLOCK = pygame.time.Clock()

# list to hold ids for unique ids
UNIQUE_EVENT_IDS = []

TIMED_TEXT_OBJECTS = []

def generate_event_id():
    global UNIQUE_EVENT_IDS
    id = 1
    while id in UNIQUE_EVENT_IDS:
        id += 1
    UNIQUE_EVENT_IDS.append(id)
    return pygame.USEREVENT + id

# load icon images
# Generated by Micah Perteet using Microsoft CoPilot
SLOT_ICON_IMAGES = [
    pygame.image.load("images/icons/seven.png").convert_alpha(),
    pygame.image.load("images/icons/diamond.png").convert_alpha(),
    pygame.image.load("images/icons/bell.png").convert_alpha(),
    pygame.image.load("images/icons/horseshoe.png").convert_alpha(),
    pygame.image.load("images/icons/clover.png").convert_alpha(),
    pygame.image.load("images/icons/cherry.png").convert_alpha(),
    pygame.image.load("images/icons/triple_bar.png").convert_alpha(),
    pygame.image.load("images/icons/double_bar.png").convert_alpha(),
    pygame.image.load("images/icons/single_bar.png").convert_alpha()
]

# random slot system stuff (Isaac)
ICONS = ["7", "diamond", "bell", "horseshoe", "clover", "cherry", "triple bar", "double bar", "bar"]
rand_nums = []
mean = 0
std_dev = 1

# Image by Isaac Franklin
SLOT_BASE_IMAGE = pygame.image.load("images/slot_base.gif").convert_alpha()
SLOT_BASE_IMAGE = pygame.transform.scale_by(SLOT_BASE_IMAGE, (2.3, 2))
# class setup for icons
class icon(pygame.sprite.Sprite):
    def __init__(self, x, y):
        super().__init__()
        self.image = rand.choice(SLOT_ICON_IMAGES)
        self.rect = self.image.get_rect()   
        self.rect.center = (x, y)

    def choose_random_image(self):
        self.image = rand.choice(SLOT_ICON_IMAGES)

# class setup for slot base sprite
class slot_base(pygame.sprite.Sprite):
    def __init__(self, x, y):
        super().__init__()
        self.image = SLOT_BASE_IMAGE
        self.rect = self.image.get_rect()
        self.rect.center = (x, y)

# create group for slot base for easier
SLOT_BASE_GROUP = pygame.sprite.Group()
SLOT_BASE_GROUP.add(slot_base(CENTER[0], CENTER[1]))

# custom event for icon switching
ICON_SWITCH_EVENT = generate_event_id()

# time between pulling the lever and showing the final icons
SPIN_TIME = 1500
SPIN_CYCLE_EVENT = generate_event_id()

# timer setup for icon switching event
pygame.time.set_timer(ICON_SWITCH_EVENT, 100)

# create a sprite group and populate it with three icons
ICONS_GROUP = pygame.sprite.Group()
for i in range(3):
    ICONS_GROUP.add(icon((i * 135 + CENTER[0]) - 135, CENTER[1] - 220))

# Images by Isaac Franklin
LEVER_ANIM_FRAMES = [
    *[pygame.transform.scale_by(pygame.image.load(f"images/lever_{i}.gif").convert_alpha(), 2)
    for i in range(1, 7)]
]

# custom userevent for the lever animation
LEVER_ANIM_EVENT = generate_event_id()
pygame.time.set_timer(LEVER_ANIM_EVENT, 50)

# class setup for lever
class lever(pygame.sprite.Sprite):
    def __init__(self, x, y):
        super().__init__()
        self.current_frame = 0
        self.cycled = True
        self.image = LEVER_ANIM_FRAMES[self.current_frame]
        self.direction = "down"
        self.rect = self.image.get_rect()
        self.rect.center = (x, y)
        
    def step_animation(self):
        global spinning
        # play downward pull animation
        if self.direction == "down" and not self.current_frame == 5:
            self.current_frame += 1
            self.image = LEVER_ANIM_FRAMES[self.current_frame]
        # play upward pull animation
        elif self.direction == "up" and not self.current_frame == 0:
            self.current_frame -= 1
            self.image = LEVER_ANIM_FRAMES[self.current_frame]
        # switch direction once the animation reaches the last frame
        if self.current_frame == 5:
            self.direction = "up"
        elif self.current_frame == 0 and self.cycled == False:
            self.direction = "down"
            self.cycled = True

# adds lever to a sprite group
LEVER_GROUP = pygame.sprite.Group()
LEVER_GROUP.add(lever(CENTER[0] + 360, CENTER[1]))
LEVER = LEVER_GROUP.sprites()

# --- VARIABLES ---
# states - "menu": Main menu, "game": Gameplay, "paused": Displays pause menu
current_state = "menu"
# this flag helps insure the pause menu doesn't get updated while it is disabled
resume_requested = False

# backend variables
username = ""
money = 100
bet_amount = 10
change = 0
spin_icons = []
spinning = False
no_money_timedtext_visable = False

# --- DEFINITIONS ---
# sets the username in the main menu
def set_username(input):
    global username
    username = input

# starts the game from the main menu
def start_game():
    global current_state
    if not username == '':
        current_state = "game"
        print(username)
        MAIN_MENU.disable()
    else:
        print("Please enter your name")

# pauses the game from the game screen
def pause_game():
    if not PAUSE_MENU.is_enabled():
        PAUSE_MENU.enable()
    global current_state
    PAUSE_MENU_MONEY_LABEL.set_title("Money: " + str(money))
    current_state = "paused"

# resumes the game
def resume_game():
    global resume_requested
    resume_requested = True

# big beefy function for handling all the events
def event_handler(events):
    global money
    global no_money_timedtext_visable
    global spinning
    global change
    global spin_icons

    # loops through each event on each tick
    for event in events:
        # quit the game if the "X" is pressed
        if event.type == pygame.QUIT:
            pygame.quit()
            exit()

        # testing feature + pausing
        elif event.type == pygame.KEYDOWN:
            if current_state == "game":
                if event.key == pygame.K_p:
                    pause_game()
                if event.key == pygame.K_m:
                    money += 10
        
        # mouse clicking event for the lever
        elif event.type == pygame.MOUSEBUTTONDOWN:
            mouse_pos = event.pos
            print("Clicked", mouse_pos)
            # if clicked on lever:
            if LEVER[0].rect.collidepoint(mouse_pos) and current_state == "game" and not spinning:
                # if not enought money display the TimedText
                if money - bet_amount < 0:
                    if not no_money_timedtext_visable:
                        no_money_timedtext_visable = True
                        text = "Not enough money!"
                        width = FONT.size(text)[0]
                        TimedText(text, FONT_SIZE * 2, BLACK, 2, (CENTER[0] - width, CENTER[1] + 200))
                # else spin the lever and do the icon probability calculation
                else:
                    money -= bet_amount
                    money = round(money, 2)
                    print("Clicked Lever")
                    change, spin_icons = roll(bet_amount)
                    spinning = True
                    # start timer for spinning
                    pygame.time.set_timer(SPIN_CYCLE_EVENT, SPIN_TIME, loops=1)
                    LEVER[0].cycled = False
        
        # switch icons randomly while spinning
        elif event.type == ICON_SWITCH_EVENT and spinning:
            for icon in ICONS_GROUP:
                icon.choose_random_image()
        
        # display final icon images and update money
        elif event.type == SPIN_CYCLE_EVENT and spinning:
            spinning = False
            money += change
            money = round(money, 2)
            change = 0
            icon_id = 0
            for icon in ICONS_GROUP:
                # switch each icon to it's final image as returned from Isaac's code
                print(spin_icons[icon_id])
                if spin_icons[icon_id] is not None:
                    icon.image = SLOT_ICON_IMAGES[ICONS.index(spin_icons[icon_id])]
                else:
                    icon.image = SLOT_ICON_IMAGES[0]
                icon_id += 1

        # step the lever images when clicked
        elif event.type == LEVER_ANIM_EVENT and not LEVER[0].cycled:
            LEVER[0].step_animation()
        
        # display all TimedText objects
        elif TIMED_TEXT_OBJECTS is not []:
            for timedtext in TIMED_TEXT_OBJECTS:
                if event.type == timedtext.id:
                    timedtext.visable = False
                    TIMED_TEXT_OBJECTS.remove(timedtext)
                    if timedtext.text == "Not enough money!":
                        no_money_timedtext_visable = False

def spin():
    global rand_nums
    rand_nums = [] # Reset nums list
    for n in range(3): # Get random number and appends it to the nums list.
        rand_nums.append(np.random.normal(loc=mean, scale=std_dev))

# Rank's the values in nums to get their corresponding icon
def rank(num):
    for i in range(9):
        if abs(num) <= (.3*i):
            new_icon = (ICONS[9-i])
            return new_icon

def roll(money): # money is the players cash going into the roll.
    global rand_nums
    multi = .7 # inital multiplier
    output = []
    spin()
    for i in range(3): # Add the icons given by the rank function to the output list.
        output.append(rank(rand_nums[i]))
    print("rolling...")
    print(output) # Shows the output of the roll in the console
    print(rand_nums[0],rand_nums[1],rand_nums[2]) # (for debugging) shows the numerical output
    if output[0] == output[1] and output[1] == output [2]: # checks if all three of the outputs are the same
        multi += rand_nums[1]*3 # Multiplier for three in a row
        print("Full", output[1], "straight")
    elif output[0] == output[1] or output[1] == output[2]: # Checks if there is two of the same icon next to each other.
        multi += rand_nums[1]*2 # Multiplier for 2 in a row
        print(output[1], "straight")
    final = abs(multi)*money # multiplies the inital money going in with the multiplier
    return final, output

# class that displays text on screen for a period of time
class TimedText:
    def __init__(self, text, size, color, time, location):
        self.visable = True
        self.id = generate_event_id()
        self.font = pygame.font.Font(None, size)
        self.text = text
        self.display_text = self.font.render(text, True, color)
        pygame.time.set_timer(self.id, (time * 1000), loops=1)
        self.location = location
        TIMED_TEXT_OBJECTS.append(self)
    
    def draw(self):
            if self.visable:
                SCREEN.blit(self.display_text, self.location)

# Main menu setup
MAIN_MENU = pygame_menu.Menu(SCREEN_TITLE, SCREEN_WIDTH, SCREEN_HEIGHT, theme=pygame_menu.themes.THEME_BLUE)
MAIN_MENU.add.text_input("Name: ", onchange=set_username)
MAIN_MENU.add.button("Play", start_game)
MAIN_MENU.add.button("Quit", pygame_menu.events.EXIT)

# Pause menu setup
PAUSE_MENU = pygame_menu.Menu("Paused", SCREEN_WIDTH, SCREEN_HEIGHT, theme=pygame_menu.themes.THEME_BLUE)
PAUSE_MENU.add.label("Money: " + str(money), label_id="pause_money_label")
PAUSE_MENU_MONEY_LABEL = PAUSE_MENU.get_widget("pause_money_label")
PAUSE_MENU.add.label("") # blank label for spacing (do not remove)
PAUSE_MENU.add.button("Resume", resume_game)
PAUSE_MENU.add.button("Quit", pygame_menu.events.EXIT)

# --- CODE BEGIN HERE ---
# --- MAIN LOOP ---
# starts the main loop for the main menu
MAIN_MENU.mainloop(SCREEN)

while True:
    # event handling
    events = pygame.event.get()
    event_handler(events)
    
    # runs while game is in progress
    if current_state == "game":
        SCREEN.fill(BG_GRAY)

        # update money text
        money_text = FONT.render("Money: " + str(money), True, BLACK)
        # renders money text
        SCREEN.blit(money_text, MONEY_TEXT_POSITION)
        LEVER_GROUP.draw(SCREEN)
        SLOT_BASE_GROUP.draw(SCREEN)
        ICONS_GROUP.draw(SCREEN)
        
        if TIMED_TEXT_OBJECTS is not []:
            for timedtext in TIMED_TEXT_OBJECTS:
                timedtext.draw()

        pygame.display.flip()

    # updates screen while in pause menu
    elif current_state == "paused":
        if PAUSE_MENU.is_enabled():
            PAUSE_MENU.update(events)

            if resume_requested:
                PAUSE_MENU.disable()
                current_state = "game"
                resume_requested = False
            else:
                PAUSE_MENU.draw(SCREEN)
                pygame.display.flip()
    
    CLOCK.tick(FPS)